TravelWeb/TravelWeb/Models/ErrorViewModel.cs
using System;

namespace TravelWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TravelWeb/TravelWeb/Controllers/AboutUSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TravelWeb.Controllers
{
    public class AboutUSController : Controller
    {
        public IActionResult AboutUS()
        {
            return View();
        }


        public IActionResult Test()
        {
            return View();
        }
    }
}

TravelWeb/TravelWeb/Controllers/CarrersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TravelWeb.Controllers
{
    public class CarrersController : Controller
    {
        public IActionResult Carrers()
        {
            return View();
        }
    }
}

TravelWeb/TravelWeb/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TravelWeb.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TravelWeb/TravelWeb/Controllers/FaqController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TravelWeb.Controllers
{
    public class FaqController : Controller
    {
        public IActionResult Faq()
        {
            return View();
        }
    }
}

TravelWeb/TravelWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TravelWeb.Models;

namespace TravelWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TravelWeb/TravelWeb/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TravelWeb.Controllers
{
    public class IndexController : Controller
    {

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult _Menu()
        {
            return PartialView();
        }

        [HttpGet]
        public IActionResult Careers()
        {
            return View();

        }
        [HttpGet]
        public IActionResult AboutUs()
        {
            return View();
        }
    }
}

TravelWeb/TravelWeb/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TravelWeb.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
    }
}

TravelWeb/TravelWeb/Views/AboutUS/AboutUS.cshtml
@{
    ViewData["Title"] = "AboutUS";
    Layout = "~/Views/Shared/_layoutPage.cshtml";
}

<div class="main-cn about-page bg-white clearfix">
    <section class="breakcrumb-sc">
        <ul class="breadcrumb arrow">
            <li><a href="index-2.html"><i class="fa fa-home"></i></a></li>
            <li>About us</li>
        </ul>
    </section>
    <section class="about-cn clearfix">
        <div class="about-searved"><span>Served over</span> <ins>584,000</ins> <span>people in 45 countries</span></div>
        <div class="about-text">
            <h1>We love travel</h1>
            <div class="about-description">
                <p>Mauris convallis hendrerit posuere. In hac habitasse platea dictumst. Curabitur dapibus bibendum eros sit amet porta. Aliquam erat volutpat. Mauris a porta ligula. Nulla convallis at urna ut rutrum.</p>
                <p>Mauris convallis hendrerit posuere. In hac habitasse platea dictumst. Curabitur dapibus bibendum eros sit amet porta. Aliquam erat volutpat. Mauris a porta ligula. Nulla convallis at urna ut rutrum. Aliquam bibendum ultrices dui, eget pulvinar dolor bibendum sed. Aenean ullamcorper, nunc in lacinia tincidunt, erat eros lobortis urna, ac scelerisque velit augue aliquam ipsum. Nulla ut hendrerit lorem. Aenean sed ipsum mauris. Proin in venenatis augue, vel congue ipsum. Etiam convallis tincidunt sagittis.ac scelerisque velit augue aliquam ipsum. Nulla ut hendrerit lorem. Aenean sed ipsum mauris. Proin in venenatis augu.</p>
            </div>
        </div>
    </section>
    <section class="team">
        <div class="team-head">
            <h2>Our team</h2>
            <p>Morbi sed sollicitudin augue. Ut metus nibh, fringilla vitae mi in, aliquam ullamcorper nisl. Integer id tincidunt libero. Donec pharetra est sed suscipit efficitur. In a gravida quam. Aenean vel dolor augue. In nec lacinia enim, vitae fermentum elit. Aliquam non diam sed lectus commodo hendrerit.</p>
        </div>
        <div class="team-group row">
            <div class="team-item col-xs-6 col-md-3">
                <figure><img src="images/team/img-1.jpg" alt=""></figure>
                <h3>ROBERT SMITH</h3>
                <span>Creative Director</span>
            </div>
            <div class="team-item col-xs-6 col-md-3">
                <figure><img src="images/team/img-2.jpg" alt=""></figure>
                <h3>JHON WHITE</h3>
                <span>Designer</span>
            </div>
            <div class="team-item col-xs-6 col-md-3">
                <figure><img src="images/team/img-3.jpg" alt=""></figure>
                <h3>JACK SMITH</h3>
                <span>Developper</span>
            </div>
            <div class="team-item col-xs-6 col-md-3">
                <figure><img src="images/team/img-4.jpg" alt=""></figure>
                <h3>JHON WHITE</h3>
                <span>Designer</span>
            </div>
        </div>
    </section>
    <section class="twitter">
        <div class="bg-parallax bg-4"></div>
        <div class="twitter-cn text-center">
            <span class="icon"><i class="fa fa-twitter"></i></span>
            <div class="twitter-slide">
                <div class="twitter-item">
                    <p>
                        Etiam sodales ligula lacus. Vestibulum pellentesque purus at mauris tristique, id mollis nibh suscipit. Nunc malesuada<br>
                        consequat velit mollis laoreet. Ut feugiat est sit amet mauris tristique<br>
                        1month ago
                    </p>
                    <ul>
                        <li><span>REply</span></li>
                        <li><span>REtweets</span></li>
                        <li><span>favorite</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section class="follow-about">
        <div class="follow-group"><a href="#" title=""><i class="fa fa-facebook"></i></a> <a href="#" title=""><i class="fa fa-twitter"></i></a> <a href="#" title=""><i class="fa fa-pinterest"></i></a> <a href="#" title=""><i class="fa fa-linkedin"></i></a> <a href="#" title=""><i class="fa fa-instagram"></i></a></div>
    </section>
</div>

TravelWeb/TravelWeb/Views/Carrers/Carrers.cshtml
@{
    ViewData["Title"] = "Carrers";
    Layout = "~/Views/Shared/_layoutPage.cshtml";
}

<h2>Carrers</h2>

TravelWeb/TravelWeb/Views/Contact/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_layoutPage.cshtml";
}

<h2>Contact</h2>

TravelWeb/TravelWeb/Views/Faq/Faq.cshtml
@{
    ViewData["Title"] = "Faq";
    Layout = "~/Views/Shared/_layoutPage.cshtml";
}

<h2>Faq</h2>

TravelWeb/TravelWeb/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

TravelWeb/TravelWeb/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TravelWeb/TravelWeb/Views/Index/AboutUs.cshtml
@{
    ViewData["Title"] = "AboutUs";
    Layout = "~/Views/Shared/_layoutPage.cshtml";
}

<h2>AboutUs</h2>

TravelWeb/TravelWeb/Views/Index/Careers.cshtml
@{
    ViewData["Title"] = "Careers";
    Layout = "~/Views/Shared/_layoutPage.cshtml";
}

<h2>Careers</h2>

TravelWeb/TravelWeb/Views/Index/_Menu.cshtml
<header id="header" class="header">
    <div class="container">
        <div class="logo float-left"><a href="index-2.html" title=""><img src="images/logo-header.png" alt=""></a></div>
        <div class="bars" id="bars"></div>
        <nav class="navigation nav-c" id="navigation" data-menu-type="1200">
            <div class="nav-inner">
                <a href="#" class="bars-close" id="bars-close">Close</a>
                <div class="tb">
                    <div class="tb-cell">
                        <ul class="menu-list text-uppercase">

                            <li>
                                <a asp-controller="Index" asp-action="Index">Home</a>
                                <!--<ul class="sub-menu">

                                  <li class="current-menu-item"><a href="about.html" title="">About Us</a></li>

                                  <li><a href="contact.html" title="">Contact</a></li>
                                  <li><a href="payment.html" title="">Payment</a></li>
                                  <li><a href="element.html" title="">Element</a></li>
                                  <li><a href="404.html" title="">404</a></li>
                                  <li><a href="comingsoon.html" title="">Comingsoon</a></li>
                                </ul>-->
                            </li>
                            <li>
                                <a  title="" asp-controller="AboutUS" asp-action="AboutUS"  >About Us</a>

                            </li>
                            <li>
                                <a href="flight-list.html" title="">Flights</a>

                            </li>
                            <li>
                                <a asp-controller="Carrers" asp-action="Carrers" title="">Career</a>

                            </li>
                            <li>
                                <a asp-controller="Contact" asp-action="Contact" title="">Contact Us</a>

                            </li>
                            <li>
                                <a asp-controller="Faq" asp-action="Faq" title="">Faq</a>

                            </li>
                            <li>
                                <a asp-controller="Login" asp-action="Login" title="">Login</a>

                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</header>

TravelWeb/TravelWeb/Views/Index/_footer.cshtml
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="logo-foter"><a href="index-2.html" title=""><img src="images/logo-footer.png" alt=""></a></div>
            </div>
            <div class="col-xs-6 col-sm-3 col-md-2">
                <div class="ul-ft">
                    <ul>
                        <li><a href="about.html" title="">About</a></li>
                        <li><a href="blog.html" title="">Blog</a></li>
                        <li><a href="fqa.html" title="">FQA</a></li>
                        <li><a href="careers.html" title="">Carrers</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xs-6 col-sm-3 col-md-2">
                <div class="ul-ft">
                    <ul>
                        <li><a href="contact.html" title="">Contact Us</a></li>
                        <li><a href="#" title="">Privacy Policy</a></li>
                        <li><a href="#" title="">Term of Service</a></li>
                        <li><a href="#" title="">Security</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6 col-md-4">
                <div class="currency-lang-bottom dropdown-cn float-left">
                    <div class="dropdown-head"><span class="angle-down"><i class="fa fa-angle-down"></i></span></div>
                    <div class="dropdown-body">
                        <ul>
                            <li class="current"><a href="#" title="">English</a></li>
                            <li><a href="#" title="">Bahasa Melayu</a></li>
                            <li><a href="#" title="">Català</a></li>
                            <li><a href="#" title="">Dansk</a></li>
                            <li><a href="#" title="">Deutsch</a></li>
                            <li><a href="#" title="">Francais</a></li>
                            <li><a href="#" title="">Italiano</a></li>
                        </ul>
                    </div>
                </div>
                <div class="currency-lang-bottom dropdown-cn float-left">
                    <div class="dropdown-head"><span class="angle-down"><i class="fa fa-angle-down"></i></span></div>
                    <div class="dropdown-body">
                        <ul>
                            <li class="current"><a href="#" title="">US</a></li>
                            <li><a href="#" title="">ARS</a></li>
                            <li><a href="#" title="">ADU</a></li>
                            <li><a href="#" title="">CAD</a></li>
                            <li><a href="#" title="">CHF</a></li>
                            <li><a href="#" title="">CNY</a></li>
                            <li><a href="#" title="">CZK</a></li>
                        </ul>
                    </div>
                </div>
                <p class="copyright">© 2019 – 2020 FLIGHT DEAL US™ All rights reserved.</p>
            </div>
        </div>
    </div>
</footer>

TravelWeb/TravelWeb/Views/Login/Login.cshtml
@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_layoutPage.cshtml";
}

<div id="preloader">
        <div class="tb-cell">
            <div id="page-loading">
                <div></div>
                <p>Loading</p>
            </div>
        </div>
    </div>
<div class="main-cn element-page bg-white clearfix">
    <section class="breakcrumb-sc">
        <ul class="breadcrumb arrow">
            <li><a href="index-2.html"><i class="fa fa-home"></i></a></li>
            <li>User Reviews</li>
        </ul>
        <div class="support float-right"><small>Got a question?</small> 123-123-1234</div>
    </section>
    <section class="user-profile">
        <div class="user-form user-signup">
            <div class="row">
                <div class="col-md-5">
                    <h2 class="user-profile__title">Sign in</h2>
                    <p>Access your account information and manage your bookings.</p>
                    <div class="field-input">
                        <input type="text" class="input-text" value="Email *">
                    </div>
                    <div class="field-input">
                        <input type="text" class="input-text" value="Password *">
                    </div>
                    <div class="field-input">
                        <div class="check-box">
                            <input type="checkbox" id="checkbox">
                            <label for="checkbox">Keep me logged in</label>
                        </div>
                        <a href="#">Get a new password</a>
                    </div>
                    <div class="field-input">
                        <button class="awe-btn awe-btn-1 awe-btn-medium">Sign in</button>
                    </div>
                </div>
                <div class="col-md-5 col-md-offset-2">
                    <h2 class="user-profile__title">Sign up</h2>
                    <p>Sign up now and receive exclusive offers with huge discounts</p>
                    <div class="field-input">
                        <input type="text" class="input-text" value="First Name *">
                    </div>
                    <div class="field-input">
                        <input type="text" class="input-text" value="Last name *">
                    </div>
                    <div class="field-input">
                        <input type="text" class="input-text" value="Email *">
                    </div>
                    <div class="field-input">
                        <input type="text" class="input-text" value="Password *">
                    </div>
                    <div class="field-input">
                        <div class="check-box">
                            <input type="checkbox" id="offers">
                            <label for="offers">Send me Special Offers &amp; Promotions</label>
                        </div>
                    </div>
                    <div class="field-input">
                        <button class="awe-btn awe-btn-1 awe-btn-medium">Sign up</button>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

TravelWeb/TravelWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TravelWeb</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">TravelWeb</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - TravelWeb</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

TravelWeb/TravelWeb/Views/Shared/_layoutPage.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <title>Home Flight</title>
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400%7COpen+Sans:300,400,600" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="~/css/library/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/library/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/library/jquery-ui.min.css">
    <link rel="stylesheet" href="~/css/library/owl.carousel.css">
    <link rel="stylesheet" href="~/css/library/jquery.mb.YTPlayer.min.css">
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>
    <div id="preloader">
        <div class="tb-cell">
            <div id="page-loading">
                <div></div>
                <p>Loading</p>
            </div>
        </div>
    </div>
    <div id="wrap">
        <header id="header" class="header">
            <div class="container">
                <div class="logo float-left"><a href="index-2.html" title=""><img src="~/images/logo-header.png" alt=""></a></div>
                <div class="bars" id="bars"></div>
                <nav class="navigation nav-c" id="navigation" data-menu-type="1200">
                    <div class="nav-inner">
                        <a href="#" class="bars-close" id="bars-close">Close</a>
                        <div class="tb">
                            <div class="tb-cell">
                                <ul class="menu-list text-uppercase">

                                    <li>
                                        <a asp-controller="Index" asp-action="Index">Home</a>
                                        <!--<ul class="sub-menu">

                                          <li class="current-menu-item"><a href="about.html" title="">About Us</a></li>

                                          <li><a href="contact.html" title="">Contact</a></li>
                                          <li><a href="payment.html" title="">Payment</a></li>
                                          <li><a href="element.html" title="">Element</a></li>
                                          <li><a href="404.html" title="">404</a></li>
                                          <li><a href="comingsoon.html" title="">Comingsoon</a></li>
                                        </ul>-->
                                    </li>
                                    <li>
                                        <a title="" asp-controller="AboutUS" asp-action="AboutUS">About Us</a>

                                    </li>
                                    <li>
                                        <a href="flight-list.html" title="">Flights</a>

                                    </li>
                                    <li>
                                        <a asp-controller="Carrers" asp-action="Carrers" title="">Career</a>

                                    </li>
                                    <li>
                                        <a asp-controller="Contact" asp-action="Contact" title="">Contact Us</a>

                                    </li>
                                    <li>
                                        <a asp-controller="Faq" asp-action="Faq" title="">Faq</a>

                                    </li>
                                    <li>
                                        <a asp-controller="Login" asp-action="Login" title="">Login</a>

                                    </li>



                                </ul>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </header>
        <section class="sub-banner">
            <div class="bg-parallax bg-1"></div>
            <div class="logo-banner text-center"><a href="#" title=""><img src="~/images/logo-banner.png" alt=""></a></div>
        </section>
        <div class="main">

            <div class="container">
                @RenderBody();
            </div>
        </div>
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <div class="logo-foter"><a href="index-2.html" title=""><img src="~/images/logo-footer.png" alt=""></a></div>
                    </div>
                    <div class="col-xs-6 col-sm-3 col-md-2">
                        <div class="ul-ft">
                            <ul>
                                <li><a href="about.html" title="">About</a></li>
                                <li><a href="blog.html" title="">Blog</a></li>
                                <li><a href="fqa.html" title="">FQA</a></li>
                                <li><a href="careers.html" title="">Carrers</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-3 col-md-2">
                        <div class="ul-ft">
                            <ul>
                                <li><a href="contact.html" title="">Contact Us</a></li>
                                <li><a href="#" title="">Privacy Policy</a></li>
                                <li><a href="#" title="">Term of Service</a></li>
                                <li><a href="#" title="">Security</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4">
                        <div class="currency-lang-bottom dropdown-cn float-left">
                            <div class="dropdown-head"><span class="angle-down"><i class="fa fa-angle-down"></i></span></div>
                            <div class="dropdown-body">
                                <ul>
                                    <li class="current"><a href="#" title="">English</a></li>
                                    <li><a href="#" title="">Bahasa Melayu</a></li>
                                    <li><a href="#" title="">Català</a></li>
                                    <li><a href="#" title="">Dansk</a></li>
                                    <li><a href="#" title="">Deutsch</a></li>
                                    <li><a href="#" title="">Francais</a></li>
                                    <li><a href="#" title="">Italiano</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="currency-lang-bottom dropdown-cn float-left">
                            <div class="dropdown-head"><span class="angle-down"><i class="fa fa-angle-down"></i></span></div>
                            <div class="dropdown-body">
                                <ul>
                                    <li class="current"><a href="#" title="">US</a></li>
                                    <li><a href="#" title="">ARS</a></li>
                                    <li><a href="#" title="">ADU</a></li>
                                    <li><a href="#" title="">CAD</a></li>
                                    <li><a href="#" title="">CHF</a></li>
                                    <li><a href="#" title="">CNY</a></li>
                                    <li><a href="#" title="">CZK</a></li>
                                </ul>
                            </div>
                        </div>
                        <p class="copyright">© 2019 – 2020 FLIGHT DEAL US™ All rights reserved.</p>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script type="text/javascript" src="~/js/library/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="~/js/library/jquery-ui.min.js"></script>
    <script type="text/javascript" src="~/js/library/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/js/library/owl.carousel.min.js"></script>
    <script type="text/javascript" src="~/js/library/parallax.min.js"></script>
    <script type="text/javascript" src="~/js/library/jquery.nicescroll.js"></script>
    <script type="text/javascript" src="~/js/library/jquery.ui.touch-punch.min.js"></script>
    <script type="text/javascript" src="~/js/library/jquery.mb.YTPlayer.min.js"></script>
    <script type="text/javascript" src="~/js/library/SmoothScroll.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
    <script src="~/js/script.js"></script>
</body>

</html>